### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by stevemoser** [johnpatrickmorgan/wtfautolayout#12]
Getting a heroku error: "Application error"

**Comment by johnpatrickmorgan** [comment]
Thanks for reporting this issue. The application was crashing due to duplicate keys in the info dictionary, which [naively expected keys to be unique](https://github.com/johnpatrickmorgan/wtfautolayout/blob/4cdd04675cddf91ce71ed80a221e7113b1cbd4c0/Sources/App/Parsing/ConstraintsParser%2BInfo.swift#L23). E.g. the following input would cause a crash:
```
"<NSLayoutConstraint:0x608078 V:[DuplicateKey...]-(7)-[DuplicateKey...]   (active, names: DuplicateKey...:0x7f950028efe0, DuplicateKey...:0x7f950028e5b0 )>"
```

A fix [has now been deployed](https://github.com/johnpatrickmorgan/wtfautolayout/releases/tag/1.2.3). Thanks again.
